window.esdocSearchIndex = [
  [
    "idb-file-storage/src/idb-file-storage.js~idbfilestorage",
    "class/src/idb-file-storage.js~IDBFileStorage.html",
    "<span>IDBFileStorage</span> <span class=\"search-result-import-path\">idb-file-storage/src/idb-file-storage.js</span>",
    "class"
  ],
  [
    "idb-file-storage/src/idb-file-storage.js~idbpromisedfilehandle",
    "class/src/idb-file-storage.js~IDBPromisedFileHandle.html",
    "<span>IDBPromisedFileHandle</span> <span class=\"search-result-import-path\">idb-file-storage/src/idb-file-storage.js</span>",
    "class"
  ],
  [
    "idb-file-storage/src/idb-file-storage.js~idbpromisedmutablefile",
    "class/src/idb-file-storage.js~IDBPromisedMutableFile.html",
    "<span>IDBPromisedMutableFile</span> <span class=\"search-result-import-path\">idb-file-storage/src/idb-file-storage.js</span>",
    "class"
  ],
  [
    "idb-file-storage/src/idb-file-storage.js~getfilestorage",
    "function/index.html#static-function-getFileStorage",
    "<span>getFileStorage</span> <span class=\"search-result-import-path\">idb-file-storage/src/idb-file-storage.js</span>",
    "function"
  ],
  [
    "idb-file-storage/src/idb-file-storage.js~waitfordomrequest",
    "function/index.html#static-function-waitForDOMRequest",
    "<span>waitForDOMRequest</span> <span class=\"search-result-import-path\">idb-file-storage/src/idb-file-storage.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/idb-file-storage.js",
    "file/src/idb-file-storage.js.html",
    "src/idb-file-storage.js",
    "file"
  ],
  [
    "src/idb-file-storage.js~blob",
    "https://developer.mozilla.org/en-US/docs/Web/API/Blob",
    "src/idb-file-storage.js~Blob",
    "external"
  ],
  [
    "src/idb-file-storage.js~domrequest",
    "https://developer.mozilla.org/en/docs/Web/API/DOMRequest",
    "src/idb-file-storage.js~DOMRequest",
    "external"
  ],
  [
    "src/idb-file-storage.js~file",
    "https://developer.mozilla.org/en-US/docs/Web/API/File",
    "src/idb-file-storage.js~File",
    "external"
  ],
  [
    "src/idb-file-storage.js~idbfilestorage#clear",
    "class/src/idb-file-storage.js~IDBFileStorage.html#instance-method-clear",
    "src/idb-file-storage.js~IDBFileStorage#clear",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbfilestorage#count",
    "class/src/idb-file-storage.js~IDBFileStorage.html#instance-method-count",
    "src/idb-file-storage.js~IDBFileStorage#count",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbfilestorage#createmutablefile",
    "class/src/idb-file-storage.js~IDBFileStorage.html#instance-method-createMutableFile",
    "src/idb-file-storage.js~IDBFileStorage#createMutableFile",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbfilestorage#get",
    "class/src/idb-file-storage.js~IDBFileStorage.html#instance-method-get",
    "src/idb-file-storage.js~IDBFileStorage#get",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbfilestorage#list",
    "class/src/idb-file-storage.js~IDBFileStorage.html#instance-method-list",
    "src/idb-file-storage.js~IDBFileStorage#list",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbfilestorage#put",
    "class/src/idb-file-storage.js~IDBFileStorage.html#instance-method-put",
    "src/idb-file-storage.js~IDBFileStorage#put",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbfilestorage#remove",
    "class/src/idb-file-storage.js~IDBFileStorage.html#instance-method-remove",
    "src/idb-file-storage.js~IDBFileStorage#remove",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbfilestorage.listfilteringoptions",
    "typedef/index.html#static-typedef-IDBFileStorage.ListFilteringOptions",
    "src/idb-file-storage.js~IDBFileStorage.ListFilteringOptions",
    "typedef"
  ],
  [
    "src/idb-file-storage.js~idbmutablefile",
    "https://developer.mozilla.org/en-US/docs/Web/API/IDBMutableFile",
    "src/idb-file-storage.js~IDBMutableFile",
    "external"
  ],
  [
    "src/idb-file-storage.js~idbpromisedfilehandle#abort",
    "class/src/idb-file-storage.js~IDBPromisedFileHandle.html#instance-method-abort",
    "src/idb-file-storage.js~IDBPromisedFileHandle#abort",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbpromisedfilehandle#active",
    "class/src/idb-file-storage.js~IDBPromisedFileHandle.html#instance-get-active",
    "src/idb-file-storage.js~IDBPromisedFileHandle#active",
    "member"
  ],
  [
    "src/idb-file-storage.js~idbpromisedfilehandle#append",
    "class/src/idb-file-storage.js~IDBPromisedFileHandle.html#instance-method-append",
    "src/idb-file-storage.js~IDBPromisedFileHandle#append",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbpromisedfilehandle#close",
    "class/src/idb-file-storage.js~IDBPromisedFileHandle.html#instance-method-close",
    "src/idb-file-storage.js~IDBPromisedFileHandle#close",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbpromisedfilehandle#getmetadata",
    "class/src/idb-file-storage.js~IDBPromisedFileHandle.html#instance-method-getMetadata",
    "src/idb-file-storage.js~IDBPromisedFileHandle#getMetadata",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbpromisedfilehandle#mode",
    "class/src/idb-file-storage.js~IDBPromisedFileHandle.html#instance-get-mode",
    "src/idb-file-storage.js~IDBPromisedFileHandle#mode",
    "member"
  ],
  [
    "src/idb-file-storage.js~idbpromisedfilehandle#queuedwrite",
    "class/src/idb-file-storage.js~IDBPromisedFileHandle.html#instance-method-queuedWrite",
    "src/idb-file-storage.js~IDBPromisedFileHandle#queuedWrite",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbpromisedfilehandle#readasarraybuffer",
    "class/src/idb-file-storage.js~IDBPromisedFileHandle.html#instance-method-readAsArrayBuffer",
    "src/idb-file-storage.js~IDBPromisedFileHandle#readAsArrayBuffer",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbpromisedfilehandle#readastext",
    "class/src/idb-file-storage.js~IDBPromisedFileHandle.html#instance-method-readAsText",
    "src/idb-file-storage.js~IDBPromisedFileHandle#readAsText",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbpromisedfilehandle#truncate",
    "class/src/idb-file-storage.js~IDBPromisedFileHandle.html#instance-method-truncate",
    "src/idb-file-storage.js~IDBPromisedFileHandle#truncate",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbpromisedfilehandle#waitforqueuedwrites",
    "class/src/idb-file-storage.js~IDBPromisedFileHandle.html#instance-method-waitForQueuedWrites",
    "src/idb-file-storage.js~IDBPromisedFileHandle#waitForQueuedWrites",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbpromisedfilehandle#write",
    "class/src/idb-file-storage.js~IDBPromisedFileHandle.html#instance-method-write",
    "src/idb-file-storage.js~IDBPromisedFileHandle#write",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbpromisedfilehandle.metadata",
    "typedef/index.html#static-typedef-IDBPromisedFileHandle.Metadata",
    "src/idb-file-storage.js~IDBPromisedFileHandle.Metadata",
    "typedef"
  ],
  [
    "src/idb-file-storage.js~idbpromisedmutablefile#getfile",
    "class/src/idb-file-storage.js~IDBPromisedMutableFile.html#instance-method-getFile",
    "src/idb-file-storage.js~IDBPromisedMutableFile#getFile",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbpromisedmutablefile#open",
    "class/src/idb-file-storage.js~IDBPromisedMutableFile.html#instance-method-open",
    "src/idb-file-storage.js~IDBPromisedMutableFile#open",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbpromisedmutablefile#persist",
    "class/src/idb-file-storage.js~IDBPromisedMutableFile.html#instance-method-persist",
    "src/idb-file-storage.js~IDBPromisedMutableFile#persist",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbpromisedmutablefile#persistasfilesnapshot",
    "class/src/idb-file-storage.js~IDBPromisedMutableFile.html#instance-method-persistAsFileSnapshot",
    "src/idb-file-storage.js~IDBPromisedMutableFile#persistAsFileSnapshot",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbpromisedmutablefile#runfilerequestgenerator",
    "class/src/idb-file-storage.js~IDBPromisedMutableFile.html#instance-method-runFileRequestGenerator",
    "src/idb-file-storage.js~IDBPromisedMutableFile#runFileRequestGenerator",
    "method"
  ],
  [
    "src/idb-file-storage.js~idbrequest",
    "https://developer.mozilla.org/en-US/docs/Web/API/IDBRequest",
    "src/idb-file-storage.js~IDBRequest",
    "external"
  ]
]